SCBJ-7/SCBJ-BE

.github/workflows/gradle.yml
=> feat: github action CI 도입

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .gitignore
=> PR 및 Issue template을 작성하다. (main에 들어갈 PR)

Dockerfile
- Close #2 
- 잘못하고, 빈 Dockerfile을 올렸네요
=> Docker file 수정

src/main/java/com/yanolja/scbj/domain/alarm/repository/AlarmRepository.java
- Close #38 
- alarm Repository가 없어서 생성했습니다.
=> feat: AlarmRepository 생성

src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/RoomTheme.java
=> fix: roomTheme 필드 값 변경

src/main/java/com/yanolja/scbj/domain/member/entity/Member.java, src/main/java/com/yanolja/scbj/domain/member/entity/YanoljaMember.java, src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
- Close #44 
- 세 개의 entity class에서 Mapping관계가 이상하다고 생각해 수정했습니다.
- 고쳐야 할 부분이 있으면 말씀해주세요.!
=> member, yanoljamember, product entity 수정

src/main/java/com/yanolja/scbj/global/common/ResponseDTO.java
- Close #35 
- code가 중복으로 생성되서 삭제했습니다!
=> fix: responseDTO에 code 중복 생성 제거

src/main/java/com/yanolja/scbj/ScbjApplication.java, src/main/java/com/yanolja/scbj/global/common/BaseEntity.java
어노테이션 빠진거 추가해놨슴둥!! 
- https://velog.io/@kdohyeon/Spring-EnableJpaAuditing
=> fix: base Entity 수정

src/test/java/com/yanolja/scbj/util/ControllerTestWithoutSecurityHelper.java
=> feat: security 테스트 헬퍼 클래스 작성

src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java, src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
=> fix: 패키지 오류 수정

src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java, src/main/java/com/yanolja/scbj/domain/member/entity/Member.java, src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
- Closes #74 
- 기능이 많이 만들어질거라, 편하실 때 봐주세요. (저녁 7시 이후는 개인적인 안정을 취하세요!)
- 빨리 안봐도 돼요!
=> 유저 이름 변경 API구현

.github/workflows/gradle.yml
=> CI 스크립트를 수정합니다!

src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java, src/main/java/com/yanolja/scbj/domain/member/dto/response/MemberResponse.java, src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java, src/main/java/com/yanolja/scbj/domain/member/util/MemberMapper.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
=> 회원 정보 조회 기능 구현

src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java, src/main/java/com/yanolja/scbj/domain/member/entity/Member.java, src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java, src/main/java/com/yanolja/scbj/domain/member/validation/Phone.java, src/main/java/com/yanolja/scbj/global/exception/GlobalRestControllerAdvice.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
- closes #73 
- 천천히 해주셔도 됩니다.!!
=> 유저 핸드폰 번호 변경 기능 구현

src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java, src/main/java/com/yanolja/scbj/domain/member/dto/response/MemberResponse.java, src/main/java/com/yanolja/scbj/domain/member/exception/NotFoundYanoljaMember.java, src/main/java/com/yanolja/scbj/domain/member/repository/YanoljaMemberRepository.java, src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java, src/main/java/com/yanolja/scbj/domain/member/util/MemberMapper.java, src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
=> 야놀자 계정 연동하기 기능 구현

build.gradle, src/main/java/com/yanolja/scbj/domain/member/config/EmailConfig.java, src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java, src/main/java/com/yanolja/scbj/domain/member/exception/EmailServcerException.java, src/main/java/com/yanolja/scbj/domain/member/service/MailService.java, src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java, src/main/resources/application-local.yml, src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/member/service/MailServiceTest.java, src/test/resources/application.yml
- Close #25 
- 천천히 봐주세요~
- 현재는 #81 이 진행되야 -> CI가 가능할 거 같습니다!
- https://green-bin.tistory.com/83
- 이번 PR이 Merge되면 EmailSerivce에 대한 설정이 필요합니다. 
[참고 노션 페이지](https://www.notion.so/Application-yml-c8680a636c054628acf5610e239ed58c)
- 위 노션 페이지 참고하셔서 바로 설정해도 상관없으니 보면 설정 부탁드려요!! (이메일 관련 키는 노출되면 안됩니다.ㅜ)
=> 이메일 인증 번호 발급 기능 구현

src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Hotel.java, src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductFindResponse.java, src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
- Close #37
- 착한 리뷰 부탁드려요^^ ^^
=> 상품 상세 조회시 이미지 값 추가

src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java, src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductPostRequest.java, src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
- Close #86 
- 기획 추가에 따른 계좌 update 로직을 추가했습니다.
- 양도글 작성 기획이 계속 변동되므로 계속 수정해야하는 api입니다.
=> Feature/#86 create product 1.5sprint

src/main/java/com/yanolja/scbj/domain/member/entity/Member.java, src/main/java/com/yanolja/scbj/domain/member/entity/MemberAgreement.java, src/main/java/com/yanolja/scbj/domain/member/util/MemberMapper.java
=> 회원 가입 시, 약관 생성

src/main/java/com/yanolja/scbj/global/config/SecurityConfig.java, src/main/java/com/yanolja/scbj/global/config/jwt/JwtRequestFilter.java, src/main/java/com/yanolja/scbj/global/exception/GlobalRestControllerAdvice.java
- Close #94 
- 현재 예외 처리, 응답으로 보내고 있는 게 API명세서와 달라서 수정했습니다!
* Reviewer 분들은 코드 리뷰 시 좋은 코드의 방향을 제시하되, 코드 수정을 강제하지 말아 주세요.
* Reviewer 분들은 좋은 코드를 발견한 경우, 칭찬과 격려를 아끼지 말아 주세요.
* Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 3일 이내에 진행해 주세요.
* P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
* P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
* P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)
=> 글로벌 및 Security 예외 처리 수정

src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java, src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberEmailRequest.java, src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberSignInRequest.java, src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberSignUpRequest.java, src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdateAccountRequest.java, src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdateNameRequest.java, src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdatePasswordRequest.java, src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdatePhoneRequest.java, src/main/java/com/yanolja/scbj/domain/member/dto/request/RefreshRequest.java, src/main/java/com/yanolja/scbj/domain/member/validation/AccessToken.java, src/main/java/com/yanolja/scbj/domain/member/validation/Password.java, src/main/java/com/yanolja/scbj/domain/member/validation/Phone.java, src/main/java/com/yanolja/scbj/domain/member/validation/ValidationGroups.java, src/main/java/com/yanolja/scbj/domain/member/validation/ValidationSequence.java, src/main/java/com/yanolja/scbj/domain/member/validation/validator/PasswordValidator.java, src/main/java/com/yanolja/scbj/domain/member/validation/validator/PhoneValidator.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java
- Close #96 
- 오늘 안으로 PR이 들어가야 될 거 같습니다!
- 파일 Changed는 많지만, 수정 내용은 적습니다.
=> 유효성 처리 순서 명시

src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductPostRequest.java, src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductPostResponse.java, src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java, src/main/java/com/yanolja/scbj/domain/reservation/dto/response/ReservationFindResponse.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java, src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverterTest.java, src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationServiceTest.java
- ing #105 
- dto를 record로 변경함에 따라 Builder 변경했습니다.
- 비즈니스로직, 테스트 로직 따로 pr을 올리려했으나 실수로 같이 올렸습니다 ㅠㅠ! 다음부턴 주의하고 올릴게요 👍 
=> refactor: dto를 record로 변경

src/main/java/com/yanolja/scbj/domain/payment/controller/HistoryController.java, src/main/java/com/yanolja/scbj/domain/payment/dto/response/SpecificPurchasedHistoryResponse.java, src/main/java/com/yanolja/scbj/domain/payment/exception/PaymentHistoryNotFoundException.java, src/main/java/com/yanolja/scbj/domain/payment/repository/PaymentHistoryRepository.java, src/main/java/com/yanolja/scbj/domain/payment/service/HistoryService.java, src/main/java/com/yanolja/scbj/domain/payment/service/PaymentHistoryDtoConverter.java
- ing #107 
- 구매내역 상세 조회를 위한 Controller, Service, DTO 완성
- 예외처리 추가
- unit test는 추후 진행하도록 하겠습니다.
=> feat: 구매내역 조회 비즈니스 로직 구현

src/main/java/com/yanolja/scbj/domain/member/controller/MemberAuthRestController.java, src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
=> 멤버 서비스 응답 메시지 변경

src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java, src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductFindResponse.java, src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
=> 1차 회고에 맞춰 수정

src/main/java/com/yanolja/scbj/domain/payment/controller/PaymentRestController.java, src/main/java/com/yanolja/scbj/domain/payment/dto/request/PaymentReadyRequest.java, src/main/java/com/yanolja/scbj/domain/payment/dto/response/PaymentAmountResponse.java, src/main/java/com/yanolja/scbj/domain/payment/dto/response/PaymentApproveResponse.java, src/main/java/com/yanolja/scbj/domain/payment/dto/response/PaymentCancelResponse.java, src/main/java/com/yanolja/scbj/domain/payment/dto/response/PaymentReadyResponse.java, src/main/java/com/yanolja/scbj/domain/payment/entity/PaymentHistory.java, src/main/java/com/yanolja/scbj/domain/payment/service/PaymentService.java, src/main/resources/application-local.yml
- Close #111 
- 카카오페이 결제 요청, 요청 승인, 결제 취소 api 구현 완료했습니다 ! 
- **.env파일에 추가하셔야 할 apikey는 따로 전달해드리겠습니다 !!** 
=> feat: 카카오페이 결제 구현 완료

src/test/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentServiceTest.java
- 결제 페이지 조회 로직 테스트 코드 작성
- Close #110
- 기존 pr 닫고 새로 열었습니다.
- #127
=> test: 결제 페이지 조회 테스트 코드 작성

src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java, src/main/java/com/yanolja/scbj/domain/alarm/util/AlarmMapper.java, src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java, src/main/resources/application-local.yml, src/test/java/com/yanolja/scbj/domain/alarm/service/AlarmServiceTest.java
=> 알림 생성 서비스 구현하다.

src/main/java/com/yanolja/scbj/domain/alarm/dto/AlarmResponse.java, src/main/java/com/yanolja/scbj/domain/alarm/entity/Alarm.java, src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java, src/main/java/com/yanolja/scbj/domain/alarm/util/AlarmMapper.java, src/test/java/com/yanolja/scbj/domain/alarm/controller/AlarmRestControllerTest.java
- close #159 
- 이슈 내용을 확인해주세요!
- 이 PR 머지 시, 필드 하나가 추가되기 때문에!! 머지 되자마자 배포 서버 알람 DB에 컬럼 추가하고자 하는 걸 인지해주세요!
> 알람 서비스 쪽, 조회 부분이 핵심 로직입니다.
=> 알람에 읽음 여부를 추가합니다!! 

src/main/java/com/yanolja/scbj/global/config/jwt/JwtRequestFilter.java, src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
=> jwt parsing시 발생할 수 있는 base64 예외 핸들링 및및 error code 수정

src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java, src/main/java/com/yanolja/scbj/global/exception/ForbbidenException.java, src/main/java/com/yanolja/scbj/global/util/SecurityUtil.java
=> jwtUtill 사용 시, 권한이 없는 유저에 대해 예외 처리 추가

build.gradle, src/main/java/com/yanolja/scbj/domain/member/service/MailService.java, src/main/java/com/yanolja/scbj/global/config/RetryConfig.java, src/main/java/com/yanolja/scbj/global/config/fcm/FCMService.java, src/test/java/com/yanolja/scbj/domain/fcm/FCMIntegrationTest.java, src/test/java/com/yanolja/scbj/global/config/AbstractContainersSupport.java
=> FCM 서버 예외 시, 재시도 및 메일 전송 보상 처리

src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdateAccountRequest.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
=> 계좌 번호 관련 유효성 추가 

src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/exception/ProductNotForSaleException.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java, src/main/java/com/yanolja/scbj/domain/product/entity/Product.java, src/main/java/com/yanolja/scbj/global/config/RetryConfig.java, src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java, src/main/java/com/yanolja/scbj/global/exception/InternalServerException.java, src/main/resources/application-local.yml
- Close #180
- 리트라이 로직
- 예외처리 추가되었습니다.
=> 결제 로직 수정 + 보완

build.gradle, src/main/java/com/yanolja/scbj/global/config/fcm/FCMController.java, src/main/java/com/yanolja/scbj/global/config/fcm/FCMRestController.java, src/main/resources/templates/FcmTest.html
- Close #183 
- 어느정도 연결이 되면, 다시 (testController)파일 삭제 후 배포하고자 합니다.!!
- /v1/fcm 에 view가 있어서 거기서 테스트 가능합니다 (알림)
=> FE 푸쉬 알림 TEST용 Controller 생성

src/main/java/com/yanolja/scbj/domain/member/exception/NotExpiredTokenException.java, src/main/java/com/yanolja/scbj/domain/member/service/MemberAuthService.java, src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
=> 토큰 재발급 시, 유효한 액세스 토큰에 대한 유효성 처리

src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/request/PaymentReadyRequest.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
=> 결제 로직 일부 리팩토링했습니드아

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
=> refactor: 이미지로 인한 중복상품 생성으로 인한 리팩토링

src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductFindResponse.java, src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java, src/main/java/com/yanolja/scbj/global/util/SecurityUtil.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
=> 상세 조회 시 상품 판매자 체크 로직 추가

src/main/java/com/yanolja/scbj/domain/product/entity/Product.java, src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
=> fix: product entity 수정으로 stock 1로 수정

src/main/java/com/yanolja/scbj/domain/paymentHistory/entity/PaymentAgreement.java
- Close #215
- 결제 약관 엔티티 속성 추가했습니다.
=> feat: 결제 약관 엔티티 속성 추가

src/main/java/com/yanolja/scbj/domain/product/entity/Product.java, src/main/java/com/yanolja/scbj/domain/product/entity/ProductAgreement.java
=> feat: product, productAgreement entity 생성

src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java, src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java, src/main/java/com/yanolja/scbj/global/exception/IsNotYanoljaMemberException.java, src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
=> 계좌 등록 시, 연동된 계정이어야 합니다.

src/main/java/com/yanolja/scbj/domain/paymentHistory/entity/PaymentAgreement.java
- Close #217 
- 컬럼 기본값을 추가했습니다.
=> feat: 컬럼의 기본 값 추가

.github/workflows/deploy.yml, .github/workflows/gradle.yml, docker-compose.yml
=> REDISSON 의존성이 생김에 따른 CI, CD 스크립트를 추가합니다.

src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductPostRequest.java, src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
=> fix: product, productAgreement 수정에 따른 양도글 작성 로직 변경

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
=> fix: 페이지네이션 문제로 인한 테스트

.github/workflows/deploy.yml, .github/workflows/gradle.yml
=> CI, CD redis container 삭제

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
=> hotfix: 쿼리문 수정

src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/request/PaymentReadyRequest.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/PaymentReadyResponse.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/PreparePaymentResponse.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/PaymentApiService.java, src/test/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/paymentHistory/service/KakaoPaymentServiceTest.java
=> 결제 로직 테스트 코드 작성

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
=> fix: alias Exception 으로 인한 수정

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
=> fix: baseEnttiy로 인한 수정

src/main/java/com/yanolja/scbj/global/common/ResponseDTO.java
=> fix: responseDTO 수정

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
=> fix: 네이티브 쿼리 수정

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
=> fix: 네이티브 쿼리 오류 해결

build.gradle, src/main/java/com/yanolja/scbj_crawling/CrawlerApplication.java, src/main/java/com/yanolja/scbj_crawling/mockData/CreateMockData.java
- Close #248
- 중간 리뷰 반영입니다.
- 크롤링만 수행할 수 있는 어플리케이션을 따로 패키지 분리해서 만들었습니다.
=> 크롤러 어플리케이션 분리

src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java, src/main/java/com/yanolja/scbj/domain/product/service/CityDtoConverter.java, src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
=> refactor: main 페이지 전채 수정

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
=> fix: SELECT 문 추가

src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java
=> 판매 가능 상품인지 체크하는 로직 수정

src/main/java/com/yanolja/scbj/domain/member/util/MemberMapper.java, src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java, src/main/java/com/yanolja/scbj/domain/product/util/ProductMapper.java
- Close #257 
- productMapper 생성
- 예외처리 메소드로 분리
=> refactor: 양도글(상품) 작성 리팩토링 완료

src/main/java/com/yanolja/scbj/domain/paymentHistory/repository/PaymentHistoryRepository.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SettlementService.java, src/main/java/com/yanolja/scbj/global/config/SchedulerConfig.java, src/main/resources/application-local.yml, src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SettlementServiceTest.java, src/test/resources/application.yml
- Close #237 
- schedule cron 시간이 외부에 노출되면 안좋을 것 같아서 yml, .env로 빼뒀습니다
- https://github.com/SCBJ-7/SCBJ-BE/discussions/246
=> 정산 시 벌크연산 도입

build.gradle, src/main/java/com/yanolja/scbj_crawling/CrawlerApplication.java, src/main/java/com/yanolja/scbj_crawling/mockData/CreateMockData.java
- Close #248
- 기존 pr과 같습니다. 오류 해결을 위해 삭제했고, 다시 올립니다.
=> 크롤링 어플리케이션 분리

src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/request/PaymentReadyRequest.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
=> hotfix 결제 시 약관 추가

src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
=> fix: 체크인 지났는지 확인 로직 수정

src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/request/PaymentReadyRequest.java
=> feat: isOverAge json property 추가

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
=> hotFix: brunch 로 변경

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
=> hotFix: 날짜 필터링 수정

src/main/java/com/yanolja/scbj/global/util/TimeValidator.java
=> hotfix 2차양도 가격 설정 체크 로직 수정

src/main/java/com/yanolja/scbj/domain/alarm/dto/CheckInAlarmResponse.java, src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/entity/PaymentHistory.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/repository/PaymentHistoryRepository.java, src/main/resources/application-local.yml, src/test/java/com/yanolja/scbj/domain/alarm/repository/AlarmRepositoryTest.java
=> 체크인 24시간 전 알림 구현

src/main/java/com/yanolja/scbj/domain/product/service/PricingHelper.java
=> Hotfix: 메인페이지 퍼센트 계산 로직 변경

src/main/java/com/yanolja/scbj/domain/product/service/PricingHelper.java
=> HotFIx: 2차가격 보여지는 문제 해결

src/main/java/com/yanolja/scbj/global/util/TimeValidator.java
=> Hotfix 2차 양도가겨 변경 시점 수정

src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/PaymentSuccessResponse.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/PaymentApiService.java, src/test/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestControllerTest.java
=> 결제 시 반환 값 추가

src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java, src/test/java/com/yanolja/scbj/domain/product/repository/ProductMainRepositoryTest.java
=> Hotfix: 할인순 정렬, 테마 정렬

src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
=> HotFIx: 우선순위 변경

src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/request/redis/PaymentRedisRequest.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/KakaoPayAmountResponse.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/KakaoPayApproveResponse.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/KakaoPayCancelResponse.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/KakaoPayReadyResponse.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/redis/PaymentRedisResponse.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentAgreementMapper.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentHistoryMapper.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentRedisMapper.java, src/main/java/com/yanolja/scbj/domain/product/entity/Product.java, src/main/java/com/yanolja/scbj/domain/product/util/ProductMapper.java, src/test/java/com/yanolja/scbj/domain/paymentHistory/service/KakaoPaymentServiceTest.java
=> 결제 로직 리팩토링

build.gradle, src/docs/asciidoc/product/product-api.adoc, src/test/java/com/yanolja/scbj/docs/RestDocsConfig.java, src/test/java/com/yanolja/scbj/docs/RestDocsSupport.java
=> restdocs 설정

src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
=> fix: url 수정

src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
=> 구매 내역이 저장되기 이전에 알림 생성 서비스가 실행되는 거 방지

src/main/java/com/yanolja/scbj/global/config/fcm/FCMService.java
=> 알람 비동기 executor 명시

src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
- Close #1
- 서버 로그를 보며, 알람 생성이 안되는 거 같았는데, 잘 되고 있었네요. 다시 원상 복구
=> hotfix:알람 생성 비동기화

src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
=> hotfix: create Alarm 같은 쓰레드가 당담하게 변경

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
=> Hotfix: 쿼리 수정

src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverter.java
=> Hotfix: paymentHistory.createdAt 으로 수정

src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/SaleHistoryResponse.java, src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java, src/test/java/com/yanolja/scbj/domain/paymentHistory/paymentController/PaymentHistoryRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryServiceTest.java
=> Hotfix: 로직변경

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
=> Hotfix: roomName 변경

src/main/java/com/yanolja/scbj/domain/product/service/CityMapper.java, src/main/java/com/yanolja/scbj/domain/product/service/WeekendMapper.java
=> Hotfix: getRoomName 으로 변경

src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentHistoryRestController.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryService.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverter.java, src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java, src/test/java/com/yanolja/scbj/domain/paymentHistory/paymentController/PaymentHistoryRestControllerTest.java, src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryServiceTest.java, src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverterTest.java
=> Hot fix/payment history

src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverter.java
=> hotFix: 판매목록과 하루차이나는 문제 해결

src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java, src/main/java/com/yanolja/scbj/global/config/fcm/FCMService.java
=> 푸쉬 알림 상태 확인을 위한 로깅

src/test/resources/application.yml
=> 체크인 알림 관련 test/**/ application.yml 환경 변수 추가

src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentService.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentHistoryMapper.java
=> 결제 페이지 조회 로직 리팩토링

src/docs/asciidoc/product/product-api.adoc, src/test/java/com/yanolja/scbj/docs/RestDocsSupport.java, src/test/java/com/yanolja/scbj/domain/product/docs/ProductRestControllerDocsTest.java
=> 상품 상세 조회 restdocs

src/docs/asciidoc/paymentHistory/paymentHistory-api.adoc, src/test/java/com/yanolja/scbj/domain/paymentHistory/docs/PaymentHistoryRestControllerDocsTest.java
=> docs: 구매내역 상세 조회 api RESTDOCS 작업

src/main/java/com/yanolja/scbj/domain/paymentHistory/repository/PaymentHistoryRepository.java, src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryService.java
=> hotFix: 파라미터 값 수정

src/main/java/com/yanolja/scbj/domain/reservation/service/ReservationService.java, src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationServiceTest.java
=> hotfix: 판매내역 삭제시, 예약내역에 다시 보여주도록 수정

src/docs/asciidoc/product/product-api.adoc, src/test/java/com/yanolja/scbj/domain/product/docs/ProductRestControllerDocsTest.java
=> 상품 삭제 restdocs 

src/main/java/com/yanolja/scbj/domain/paymentHistory/repository/PaymentHistoryRepository.java
=> hotfix: 상품 중복으로 인한 group by 문 추가

src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java, src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java, src/main/java/com/yanolja/scbj/domain/reservation/service/ReservationService.java, src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java, src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationServiceTest.java
- hotfix 입니다
- 상품 삭제 관련 로직 모두 변경했습니다.
=> Hotfix 상품 삭제 로직 변경

src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java, src/main/java/com/yanolja/scbj/global/util/TimeValidator.java
=> 오타 수정, 필요 없는 코드 삭제

src/docs/asciidoc/payment/payment-api.adoc, src/test/java/com/yanolja/scbj/domain/paymentHistory/docs/PaymentHistoryRestControllerDocsTest.java
=> docs: 결제 성공 실패 restdocs 작성완료

src/test/java/com/yanolja/scbj/docs/RestDocsSupport.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberAuthRestControllerDocsTest.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerDocsTest.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java, src/test/java/com/yanolja/scbj/util/RestDocsHelper.java
- Close #318 
로그인이 필요한 API는
RestDocsSupport.class 내의 
```java
protected RequestHeadersSnippet jwtHeader() {
return requestHeaders(headerWithName("Authorization").description("JWT 액세스 토큰"));
}
```
를 사용해주세요!!
=> 멤버 도메인 RestDocsTest 작성

src/docs/asciidoc/alarm/alarm-api.adoc, src/docs/asciidoc/member/member-api.adoc, src/test/java/com/yanolja/scbj/domain/alarm/controller/AlarmRestControllerDocsTest.java, src/test/java/com/yanolja/scbj/domain/alarm/repository/AlarmRepositoryTest.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberAuthRestControllerDocsTest.java, src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerDocsTest.java, src/test/java/com/yanolja/scbj/domain/member/service/MemberAuthServiceTest.java, src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java, src/test/java/com/yanolja/scbj/global/helper/TestConstants.java
=> 멤버 및 알람 도메인의 Rest Docs 작성

src/main/java/com/yanolja/scbj/domain/member/controller/MemberAuthRestController.java, src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java, src/main/java/com/yanolja/scbj/global/config/CustomUserDetailsService.java, src/main/java/com/yanolja/scbj/global/config/EmailConfig.java, src/main/java/com/yanolja/scbj/global/config/SecurityConfig.java, src/main/java/com/yanolja/scbj/global/config/jwt/JwtRequestFilter.java
=> 멤버 도메인 리팩토링

src/docs/asciidoc/product/product-api.adoc, src/test/java/com/yanolja/scbj/docs/RestDocsSupport.java, src/test/java/com/yanolja/scbj/domain/product/docs/ProductRestControllerDocsTest.java
=> 상품 Docs 헤더 추가

src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
=> refactor: 메인페이지 비지니스 로직 리팩토링
